#cloud-config
coreos:
    units:
      - name: coreos-cloudinit-vagrant.path
        command: start
        runtime: no
        content: |
          [Path]
          PathExists=/var/lib/coreos-vagrant/user-data
          Unit=user-cloudinit@var-lib-coreos\x2dvagrant-user\x2ddata.service
    oem:
      id: vagrant
      name: Vagrant
      home-url: http://www.vagrantup.com/
      bug-report-url: https://github.com/coreos/coreos-overlay
