#!/bin/bash
# Copyright (c) 2014 The CoreOS Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

# Look up the currently mounted usr or root device.
if mountpoint -q /usr; then
    dev=$(findmnt -n --raw --output=source --target=/usr)
else
    dev=$(findmnt -n --raw --output=source --target=/)
fi

# Mark the root as successfully booted (success=1, tries=0).
cgpt add -S1 -T0 "${dev}"
# Mark the root as highest priority
cgpt prioritize "${dev}"
