#!/bin/bash

if ! [[ -f unittest_key.pub.pem || -f unittest_key2.pub.pem ]]; then
    echo "ERROR: tests much run in the build output directory" >&2
    exit 99
fi

# If running in an out-of-tree build grab the private test keys
if ! [[ -f unittest_key.pem && -f unittest_key2.pem ]]; then
    srcdir="$(dirname "$0")"
    cp "${srcdir}/unittest_key.pem" "${srcdir}/unittest_key2.pem" ./
    if [[ $? -ne 0 ]]; then
        echo "ERROR: failed to copy private test keys to build directory" >&2
        exit 99
    fi
fi

./update_engine_unittests --gtest_filter='-*.RunAsRoot*'
