#!/bin/bash

# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Emerges necessary packages for building and testing the update engine. This
# allows incremental building, bypassing ebuild dependency resolution.

set -ex

sudo USE="-crash cros-debug" emerge -DNuv1 --selective=n "$@" \
  chromeos-base/hard-host-depends \
  chromeos-base/libchrome \
  chromeos-base/metrics \
  chromeos-base/vboot_reference \
  dev-cpp/gmock \
  dev-cpp/gtest \
  dev-util/bsdiff \
  dev-util/lcov \
  sys-apps/rootdev
