#!/bin/bash

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -ex

sudo USE="-crash cros-debug" emerge -DNauv1 \
  chromeos-base/libchrome \
  chromeos-base/metrics \
  dev-cpp/gmock \
  dev-cpp/gtest \
  dev-util/bsdiff \
  dev-util/lcov \
  sys-apps/fakeroot \
  sys-apps/rootdev
