#!/bin/bash -e
# Wrapper for launching flannel via rkt.
#
# Make sure to set FLANNEL_IMAGE_TAG to an image tag published here:
# https://quay.io/repository/coreos/flannel?tab=tags Alternatively,
# override FLANNEL_IMAGE to a custom image.

function require_ev_all() {
	for rev in $@ ; do
		if [[ -z "${!rev}" ]]; then
			echo "${rev}" is not set
			exit 1
		fi
	done
}

function require_ev_one() {
	for rev in $@ ; do
		if [[ ! -z "${!rev}" ]]; then
			return
		fi
	done
	echo One of $@ must be set
	exit 1
}

if [[ -n "${FLANNEL_VER}" ]]; then
	echo FLANNEL_VER environment variable is deprecated, please use FLANNEL_IMAGE_TAG instead
fi

if [[ -n "${FLANNEL_IMG}" ]]; then
	echo FLANNEL_IMG environment variable is deprecated, please use FLANNEL_IMAGE_URL instead
fi

FLANNEL_IMAGE_TAG="${FLANNEL_IMAGE_TAG:-${FLANNEL_VER}}"

require_ev_one FLANNEL_IMAGE FLANNEL_IMAGE_TAG

FLANNEL_IMAGE_URL="${FLANNEL_IMAGE_URL:-${FLANNEL_IMG:-quay.io/coreos/flannel}}"
FLANNEL_IMAGE="${FLANNEL_IMAGE:-${FLANNEL_IMAGE_URL}:${FLANNEL_IMAGE_TAG}}"

if [[ "${FLANNEL_IMAGE%%/*}" == "quay.io" ]]; then
	RKT_RUN_ARGS="${RKT_RUN_ARGS} --trust-keys-from-https"
fi

ETCD_SSL_DIR="${ETCD_SSL_DIR:-/etc/ssl/etcd}"
if [[ -d "${ETCD_SSL_DIR}" ]]; then
	RKT_RUN_ARGS="${RKT_RUN_ARGS} \
		--volume ssl,kind=host,source=${ETCD_SSL_DIR},readOnly=true \
		--mount volume=ssl,target=${ETCD_SSL_DIR} \
	"
fi

if [[ -S "${NOTIFY_SOCKET}" ]]; then
	RKT_RUN_ARGS="${RKT_RUN_ARGS} \
		--mount volume=notify,target=/run/systemd/notify \
		--volume notify,kind=host,source=${NOTIFY_SOCKET} \
		--set-env=NOTIFY_SOCKET=/run/systemd/notify \
	"
fi

mkdir --parents /run/flannel

RKT="${RKT:-/usr/bin/rkt}"
RKT_STAGE1_ARG="${RKT_STAGE1_ARG:---stage1-from-dir=stage1-fly.aci}"
set -x
exec ${RKT} ${RKT_GLOBAL_ARGS} \
	run ${RKT_RUN_ARGS} \
	--net=host \
	--volume run-flannel,kind=host,source=/run/flannel,readOnly=false \
	--volume etc-ssl-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true \
	--volume usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true \
	--volume etc-hosts,kind=host,source=/etc/hosts,readOnly=true \
	--volume etc-resolv,kind=host,source=/etc/resolv.conf,readOnly=true \
	--mount volume=run-flannel,target=/run/flannel \
	--mount volume=etc-ssl-certs,target=/etc/ssl/certs \
	--mount volume=usr-share-certs,target=/usr/share/ca-certificates \
	--mount volume=etc-hosts,target=/etc/hosts  \
	--mount volume=etc-resolv,target=/etc/resolv.conf \
	--inherit-env \
	${RKT_STAGE1_ARG} \
	${FLANNEL_IMAGE} \
		${FLANNEL_IMAGE_ARGS} \
		-- "$@"
