.TH UPDATE-MODULES 8 "Gentoo Linux" "2007"
.SH NAME
update\-modules \- (re)generate module config files in /etc/
.SH SYNOPSIS
\fBupdate\-modules\fR \fI[options]\fR
.SH DESCRIPTION
\fBupdate\-modules\fR is a simple tool to manage the module config files found
in the /etc/ directory.

The old Linux module utilities use a single file for all their configuration.
This makes it difficult for packages to dynamically add information about their
own modules.

\fBupdate-modules\fR makes the dynamic addition of information easier by
generating the single configuration file from the many files located in
\fI/etc/modules.d/\fR.  All files in that directory are assembled together to
form \fI/etc/modules.conf\fR.

Newer Linux module utilities include support automatically for a directory of
configuration files in \fI/etc/modprobe.d/\fR.  However, to maintain backwards
compatibility with packages that do not yet support this, we still need to
assemble the contents of \fI/etc/modules.d/\fR and \fI/etc/modprobe.d/\fR and
produce the corresponding \fI/etc/modules.conf\fR and \fI/etc/modprobe.conf\fR.

Also, when requested, it is also possible to generate \fI/etc/modules.devfs\fR.
.SH OPTIONS
.TP
\fI\-\-assume-kernel=<KV>\fR
When calculating which files need to be generated, assume the kernel version
is at least the specified \fIKV\fR.
.TP
\fI\-b\fR, \fI\-\-backup\fR
When updating configuration files, make backups by renaming files with a '.old'
suffix if they are going to be updated.
.TP
\fI\-d\fR, \fI\-\-debug\fR
Run with shell debugging enabled.  Really only useful for tracking down
misbehavior.
.TP
\fI\-D\fR, \fI\-\-devfs\fR
Force generation of the deprecated \fI/etc/modules.devfs\fR file.
.TP
\fI\-f\fR, \fI\-\-force\fR
Force generation of files regardless of timestamps.  By default,
\fBupdate-modules\fR will regenerate files only when timestamps indicate that
the configuration files are out of date.
.TP
\fI\-v\fR, \fI\-\-verbose\fR
Enable verbose output since by default, \fBupdate-modules\fR only displays
information when it does something and not when it skips steps.
.SH "FILES"
There are two types of file you can put in the module directories: normal files
and exectuable files.  Normal files contain standard modules configuration
information, as described in \fBmodules.conf\fR(5) (for files in
\fI/etc/modules.d/\fR) or as described in \fBmodprobe.conf\fR(5) (for files in
\fI/etc/modprobe.d/\fR).  Executable files are executed and their output is
used as extra configuration information.  Error messages are sent to stderr and
thus do not become part of the configuration file.

.nf
\fI/etc/modules.d/\fR - config snippets for old module utilities (<= linux-2.4)
\fI/etc/modules.conf\fR - sum of all files in \fI/etc/modules.d/\fR
\fI/etc/modprobe.d/\fR - config snippets for new module utilities (>= linux-2.6)
\fI/etc/modprobe.conf\fR - sum of all files in \fI/etc/modprobe.d/\fR
.fi
.SH "REPORTING BUGS"
Please report bugs via http://bugs.gentoo.org/
.SH AUTHORS
This manual page was written by Wichert Akkerman <wakkerma@debian.org>
for the Debian GNU/Linux system.  Modified for \fIGentoo Linux\fR.
.SH "SEE ALSO"
.BR depmod (1),
.BR modules.conf (5),
.BR modprobe.conf (5)
