#!/bin/bash -e

ENV=$1
METADATA_URL="http://169.254.169.254/computeMetadata/"

if [ -z "$ENV" ]; then
        echo usage: $0 /etc/environment
        exit 1
fi

# test for rw
touch $ENV
if [ $? -ne 0 ]; then
        echo exiting, unable to modify: $ENV
        exit 1
fi

get_value() {
    curl --fail --silent --show-error \
        -H "X-Google-Metadata-Request: True" \
        "${METADATA_URL}v1/instance/$1"
}

block-until-url "${METADATA_URL}"
external_ip=$(get_value network-interfaces/0/access-configs/0/external-ip)
public_ip=$(get_value network-interfaces/0/ip)

sed -i -e '/^COREOS_PUBLIC_IPV4=/d' \
    -e '/^COREOS_PRIVATE_IPV4=/d' \
    "${ENV}"

echo COREOS_PUBLIC_IPV4=${external_ip} >> $ENV
echo COREOS_PRIVATE_IPV4=${public_ip} >> $ENV
