#!/bin/bash +x

ENV=$1

if [ -z "$ENV" ]; then
        echo usage: $0 /etc/environment
        exit 1
fi

# test for rw
touch $ENV
if [ $? -ne 0 ]; then
        echo exiting, unable to modify: $ENV
        exit 1
fi

sed -i -e '/^COREOS_PUBLIC_IPV4=/d' \
    -e '/^COREOS_PRIVATE_IPV4=/d' \
    "${ENV}"

external_ip=$(curl --retry 5 --retry-delay 2 --silent --fail \
		"http://169.254.169.254/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip" \
		-H "X-Google-Metadata-Request: True")


public_ip=$(curl --retry 5 --retry-delay 2 --silent --fail \
		"http://169.254.169.254/computeMetadata/v1/instance/network-interfaces/0/ip" \
		-H "X-Google-Metadata-Request: True")

echo COREOS_PUBLIC_IPV4=${external_ip} >> $ENV
echo COREOS_PRIVATE_IPV4=${public_ip} >> $ENV
