#!/bin/bash

METADATA_URL="http://169.254.169.254/computeMetadata/"
TMPFILE=$(mktemp /tmp/XXXXXX-cloud-init)
if [[ $? -ne 0 || ! -f "${TMPFILE}" ]]; then
	echo "Failed to create temp file for user-data" >&2
	exit 1
fi
trap "rm -f '${TMPFILE}'" EXIT

try_cloudinit() {
    local id="$1"
    local url="${METADATA_URL}v1/${id}/attributes/user-data"

    echo "Trying to fetch $id user-data..."
    curl --fail --silent --show-error \
        -H "X-Google-Metadata-Request: True" \
        -o "${TMPFILE}" "${url}"

    ret=$?
    if [[ $ret -ne 0 && $ret -ne 22 ]]; then
        echo "curl failed with error code $ret" >&2
        return $ret
    elif [[ $ret -eq 22 || ! -s "${TMPFILE}" ]]; then
        echo "$id user-data is missing or empty, skipping"
        return 0
    fi

    coreos-cloudinit --from-file="${TMPFILE}"
    return $?
}

block-until-url "${METADATA_URL}"
try_cloudinit project && try_cloudinit instance
