#!/bin/bash
# Wrapper for launching docker daemons with an appropriate backend.

set -e

parse_docker_args() {
    local flag
    while [[ $# -gt 0 ]]; do
        flag="$1"
        shift

        # treat --flag=foo and --flag foo identically
        if [[ "${flag}" == *=* ]]; then
            set -- "${flag#*=}" "$@"
            flag="${flag%=*}"
        fi

        case "${flag}" in
            -g|--graph)
                ARG_ROOT="$1"
                shift
                ;;
            -s|--storage-driver)
                ARG_DRIVER="$1"
                shift
                ;;
            *)
                # ignore everything else
                ;;
        esac
    done
}

select_docker_driver() {
    local fstype

    # mimic docker's behavior to ensure we stat the right filesystem.
    if [[ -L "${ARG_ROOT}" ]]; then
        ARG_ROOT="$(readlink -f "${ARG_ROOT}")"
    fi

    mkdir --parents --mode=0700 "${ARG_ROOT}"
    fstype=$(findmnt --noheadings --output FSTYPE --target "${ARG_ROOT}")

    case "${fstype}" in
        btrfs)
            export DOCKER_DRIVER=btrfs
            ;;
        ext4|tmpfs|xfs) # As of 4.1
            export DOCKER_DRIVER=overlay
            ;;
        *)
            # Fall back to whatever docker's default behavior is.
            ;;
    esac
}

maybe_disable_selinux() {
    case "${DOCKER_DRIVER}" in
        btrfs)
            USE_SELINUX=""
            ;;
        *)
            # Leave enabled for everything else.
            ;;
    esac
}

ARG_ROOT="/var/lib/docker"
ARG_DRIVER=""
parse_docker_args "$@"

# Do not override the driver if it is already explicitly configured.
if [[ -z "${ARG_DRIVER}" && -z "${DOCKER_DRIVER}" ]]; then
    select_docker_driver
fi

# Enable selinux except when known to be unsupported (btrfs).
USE_SELINUX="--selinux-enabled"
maybe_disable_selinux

exec docker "$@" "${USE_SELINUX}"
