#!/bin/bash

## Usage
[ $# -lt 1 -o "${1##*-}" == 'help' ] && cat << EOF && exit 1
USAGE: ${0##*/} <environment-file>

SYNOPSIS:
  Update the COREOS_* environment variables in the given file,
  based on Exoscale provided meta-data.
EOF

# Arguments
ENV="${1}"


## Update environment

# Make sure that the file is writable
touch "${ENV}"
[ $? -ne 0 ] && echo "[${0##*/}] ERROR: Unable to modify environment file (${ENV})" && exit 1

# Delete existing environment
sed -i '/^\s*COREOS_PUBLIC_IPV[46]\s*=/d;/^\s*COREOS_PRIVATE_IPV[46]\s*=/d' "${ENV}"

# Query Exoscale meta-data provider

# ... locate provider
. /usr/share/oem/bin/exoscale-provider
PROVIDER_URL="$(exoscale_provider_url)"
METADATA_URL="${PROVIDER_URL}/meta-data"
block-until-url "${METADATA_URL}/"

# ... retrieve meta-data
PUBLIC_IPV4="$(curl --silent --fail "${METADATA_URL}/public-ipv4")"
PRIVATE_IPV4="$(curl --silent --fail "${METADATA_URL}/local-ipv4")"

# Update environment
[ -n "${PUBLIC_IPV4}" ] && echo "COREOS_PUBLIC_IPV4=${PUBLIC_IPV4}" >> "${ENV}"
[ -n "${PRIVATE_IPV4}" ] && echo "COREOS_PRIVATE_IPV4=${PRIVATE_IPV4}" >> "${ENV}"

