#!/bin/bash

. /usr/share/oem/bin/exoscale-dhcp

DHCP_SERVER=$(get_dhcp_ip)
KEY_URL="http://${DHCP_SERVER}/latest/public-keys"

block-until-url "${KEY_URL}"
curl --fail -s "${KEY_URL}" | update-ssh-keys -a exoscale
