#!/bin/bash

C10N_ENDPOINT=https://core-api.appspot.com/v1/c10n/group
META_URL="http://169.254.169.254/latest"

USER_DATA=$(curl -s $META_URL/user-data)
if [ $? -ne 0 ]; then
	echo not able to ping $META_URL >> /tmp/c10n.err
	exit 1
fi

URL=$USER_DATA

echo $URL | grep -q '^https://' || (echo Coordination URL requires valid SSL; exit 1)

TMP=`mktemp`
curl -s "$USER_DATA/raw" > $TMP

if [ $? -ne 0 ]; then
	echo not able to ping $URL >> /tmp/c10n.err
	exit 1
fi


# validate ssh key
ssh-keygen -l -f $TMP > /dev/null 2>&1
if [ $? -eq 0 ]; then
	CORE_HOME=`grep "^core:" /etc/passwd | cut -d':' -f6`
	CORE_SSH=$CORE_HOME/.ssh
	[ ! -e $CORE_SSH ] && mkdir -p $CORE_SSH
        cat $TMP >> $CORE_HOME/.ssh/authorized_keys
	chown -R core: $CORE_SSH
        echo "SSH key updated"
else
        echo "Not a valid ssh key"
fi

IP_LIST=""
for IP4 in `curl -s $META_URL/meta-data/ | grep local-ipv4`; do
        IP=$(curl -s $META_URL/meta-data/$IP4)
        if [ "$IP_LIST" != "" ]; then
                IP_LIST="$IP_LIST,$IP"
        else
                IP_LIST="$IP"
        fi
done

mkdir -p /var/run/etcd
curl -s $C10N_ENDPOINT -d "c10n_url=$URL" -d"ip_list=$IP_LIST" > /var/run/etcd/bootstrap.config
