#!/bin/bash

/usr/bin/coreos-c10n

BOOTSTRAP="/var/run/etcd/bootstrap.config"

[ ! -e $BOOTSTRAP ] && echo bootstrap config missing && exit 1

MY_IP=$(curl -s $META_URL/meta-data/local-ipv4) 

if [ -z "$IPS" ]; then
	echo "becoming master..."
	exec /usr/bin/etcd 
else
	IPS=$(cat $BOOTSTRAP|tr '\n' ',')
	echo "trying $IPS"
	exec /usr/bin/etcd -C "$IPS"
fi
