#!/bin/sh -e

# Fixup the old state directory
OLD_STATE=/media/state/etcd
STATE=/var/lib/etcd

if [ -d /media/state/etcd ]; then
  cp -R ${OLD_STATE}/. ${STATE}
  rm -R ${OLD_STATE}
  chown -R etcd:etcd ${STATE}
fi
