#!/bin/bash

/usr/bin/coreos-c10n

META_URL="http://169.254.169.254/latest"
MY_IP=$(curl -s $META_URL/meta-data/local-ipv4)
BOOTSTRAP="/var/run/etcd/bootstrap.config"

# for etcd
STATE=/media/state/etcd
mkdir -p $STATE

[ ! -e $BOOTSTRAP ] && echo bootstrap config missing && exit 1

# strip blank lines
IPS=$(grep -v $MY_IP $BOOTSTRAP|grep -v '^\n$' |sed 's/$/:7001/'|tr '\n' ','|sed 's/^,//'|sed 's/,$//')

if [ -z "$IPS" ]; then
        echo "becoming master..."
        exec /usr/bin/etcd -v -h $MY_IP -d $STATE
else
        echo "trying $IPS"
        set -x
        exec /usr/bin/etcd -v -h $MY_IP -C "$IPS" -d $STATE
fi
