#!/usr/bin/env python

# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.


import dbus
import sys

bus = dbus.SystemBus()

bluez = bus.get_object('org.bluez', '/')

adapter_path = bluez.DefaultAdapter(dbus_interface='org.bluez.Manager')
adapter = bus.get_object('org.bluez', adapter_path)

device_path = adapter.FindDevice(sys.argv[1],
  dbus_interface='org.bluez.Adapter')
device = bus.get_object('org.bluez', device_path)

adapter.RemoveDevice(device, dbus_interface='org.bluez.Adapter')
